SELECT  E.EMPLOYEE_ID
     ,  MAX(E.NAME)             AS NAME
     ,  COUNT(E.EMPLOYEE_ID)    AS REPORTS_COUNT
     ,  ROUND(SUM(M.AGE) / COUNT(E.EMPLOYEE_ID), 0) AS AVERAGE_AGE
  FROM  EMPLOYEES   E
     ,  EMPLOYEES   M
 WHERE  E.EMPLOYEE_ID   = M.REPORTS_TO
 GROUP BY E.EMPLOYEE_ID
 ORDER BY E.EMPLOYEE_ID